### ISSUE TITLE
[290/390-p12] NA in Q5 when knitting

### ISSUE THREAD

**Issue by ymzhang-neo** [TheDataMine/the-examples-book#129] opened 2020-11-04 20:16 UTC
Dear @kevinamstutz , when compiling my answer for Project 12, there seems a technical issue in RMarkdown handling the potential `NA` from SQL code chunk for Question 5. 

Question 5 is about `zip_code` in the `trip` table in the Bay Area Bike Share database. There are many missing entries in `zip_code`, and the missing value is place on top of the query output. The following screenshot illustrate what I got when click the "play" button on top-right corner of the code chunk.
![f20-290-p12-sketch-q5](https://user-images.githubusercontent.com/26282248/98162631-a322a980-1eaf-11eb-9a1a-63c0e0e5abd9.png)

However, when I knit the file, the following message is shown and the knitting process failed.
```
Quitting from lines 17-22 (f20-290-p12-sketch-q5.Rmd) 
Error in if (is.numeric(first_column) && all(diff(first_column) == 1)) display_data[[1]] = as.character(first_column) : 
  missing value where TRUE/FALSE needed
Calls: <Anonymous> ... capture.output -> evalVis -> withVisible -> eval -> eval
Execution halted
```
(Please see the next comment for the complete Rmd source code that you may test with.)

A student may get the SQL code right, but get stuck at this knitting issue. I am not sure how this could be potentially fixed by RMarkdown code chunk options. One way to circumvent it is perhaps to ask the students to sort the result by `zip_code` in the descending order:
> **Hint:** You can sort the `zip_code` descendingly when counting the number of times that the values appear.

Or, do you know whether we can avoid this issue inside RMarkdown? If so, we can also just provide an instruction on that. Thank you for the consideration!

**Comment by ymzhang-neo** [comment] 2020-11-04 20:18
Below is the Rmd file that I used.
````
---
title: "f20-290-p12-sketch-q5"
output: html_document
---

```{r setup}
library(RSQLite)
con = dbConnect(
  RSQLite::SQLite(), 
  "/class/datamine/data/bay_area_bike_share/bay_area_bike_share.db"
)
```

Question 5 asks for the count of zip code appearances. 

```{sql q5-count-zip, connection=con}
-- The following SQL will create issue for Rmd knitting, possibly due to NA.
SELECT zip_code, COUNT(*) 
FROM trip
GROUP BY zip_code
LIMIT 5;
```
````

**Comment by kevinamstutz** [comment] 2020-11-04 20:18
Dear @ymzhang-neo, interesting! Looking now, thank you!

**Comment by kevinamstutz** [comment] 2020-11-04 20:33
I can confirm that it is the NA causing this:

```{sql q5-count-zip, connection=con}
SELECT zip_code, COUNT(*) FROM trip WHERE zip_code IS NOT NULL GROUP BY zip_code LIMIT 5;
```

**Comment by ymzhang-neo** [comment] 2020-11-04 20:43
Ah, I think `IS NOT NULL` is a good way of avoiding the NA! How about we add the following hint then:
> **Hint:** There could be missing values in `zip_code`. We want to avoid them via the SQL query. You can learn more about the missing values (or NULL) in SQL [here](https://www.w3schools.com/sql/sql_null_values.asp).

**Comment by kevinamstutz** [comment] 2020-11-04 20:46
I like that a lot, I'm going to add that hint. I'm still going to keep this open because this, in my opinion, is a bug of some sort. Do you agree?

**Comment by ymzhang-neo** [comment] 2020-11-04 20:47
Totally agree! Thanks @kevinamstutz for the consideration!

**Comment by lsukova** [comment] 2022-12-02 02:21
Hey @kevinamstutz I'm going to close this issue

**Closed by lsukova** 2022-12-02 02:21 UTC
